language: node_js
addons:
  apt:
    sources:
     - sourceline: 'deb https://dl.winehq.org/wine-builds/ubuntu/ trusty main'
       key_url: 'https://dl.winehq.org/wine-builds/Release.key'
    packages:
     - winehq-stable
node_js:
  - "node"
script:
  - npm run lint
  - node build.js
  - dir dist
